name: Security Vulnerability
description: Report a security vulnerability (use email for critical issues)
title: "[SECURITY] "
labels: ["security", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT**: For critical security vulnerabilities, please report via email to [security@nixline.org](mailto:security@nixline.org) instead of creating a public issue.

        Use this template only for low-severity security issues that can be discussed publicly.

  - type: checkboxes
    id: severity-check
    attributes:
      label: Severity Confirmation
      description: Please confirm this is appropriate for a public issue
      options:
        - label: This is NOT a critical vulnerability (no immediate risk of code execution, data exposure, or privilege escalation)
          required: true
        - label: This issue can be discussed publicly without increasing risk
          required: true
        - label: I have read the security policy and understand when to use email reporting
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this security issue?
      options:
        - Low (hardening opportunity, minor configuration issue)
        - Medium (potential security risk requiring specific conditions)
        - High (significant security risk - consider email reporting)
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Affected Component
      description: Which component has the security issue?
      options:
        - NixLine Baseline
        - Reusable Workflows
        - Policy Packs
        - Sync App
        - Migration Tools
        - Dependencies
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability Description
      description: Describe the security issue
      placeholder: |
        What is the security vulnerability?
        What systems or data could be affected?
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker accomplish with this vulnerability?
      placeholder: |
        An attacker could...
        This could lead to...
    validations:
      required: true

  - type: textarea
    id: conditions
    attributes:
      label: Attack Conditions
      description: What conditions are required to exploit this vulnerability?
      placeholder: |
        Requires access to...
        Only possible when...
        Depends on configuration...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be demonstrated?
      placeholder: |
        1. Configure system with...
        2. Run command...
        3. Observe security issue...
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: Do you have ideas for how to fix this issue?
      placeholder: |
        This could be mitigated by...
        Consider implementing...

  - type: input
    id: version
    attributes:
      label: Affected Version
      description: What version contains this vulnerability?
      placeholder: "stable, unstable, or specific commit"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Relevant environment information
      placeholder: |
        OS: ...
        Nix version: ...
        Configuration: ...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information about this security issue