#
# Auto-merge validated PRs
#
# Automatically merges pull requests in the .github repository when all validation
# checks pass. Ensures only validated workflow changes are deployed without requiring
# manual intervention for routine updates.
#
# Triggered by: pull_request events, check_suite completion
# Purpose: Streamline deployment of validated workflow improvements
# Safety: Only merges when ALL validation checks pass
#

name: Auto-merge validated PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]
  check_suite:
    types: [completed]

permissions:
  contents: write
  pull-requests: write
  checks: read

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Wait for validation to complete
        uses: lewagon/wait-on-check-action@v1.4.1
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'validate'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

      - name: Enable auto-merge
        if: success()
        run: gh pr merge --auto --squash "$PR_NUMBER"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
