name: Policy — flake.lock only (reusable)
on:
  workflow_call: {}
# Note: This workflow requires the following permissions:
# permissions:
#   contents: read          # To read policy configuration

permissions:
  contents: read
jobs:
  policy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with: { fetch-depth: 2 }
      - name: Ensure only flake.lock changed
        run: |
          set -euo pipefail
          base_sha=$(git rev-parse HEAD^ || git rev-parse HEAD)
          fail=false
          for f in $(git diff --name-only "$base_sha"...HEAD); do
            if [[ "$f" != "flake.lock" ]]; then
              echo "::error::Disallowed change: $f"
              fail=true
            fi
          done
          if [[ "$fail" == "true" ]]; then
            echo "Only flake.lock changes are allowed in this PR."
            exit 1
          fi
