name: NixLine Nixpkgs Validate (reusable)

on:
  workflow_call:
    inputs:
      tag_to_validate:
        description: 'Tag to validate (usually unstable)'
        required: false
        type: string
        default: 'unstable'
      promote_on_success:
        description: 'Promote to stable if validation passes'
        required: false
        type: boolean
        default: true
      stable_tag:
        description: 'Tag name for stable version'
        required: false
        type: string
        default: 'stable'

# Note: This workflow requires the following permissions:
# permissions:
#   contents: write
#   issues: write
#   pull-requests: write

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      validation_passed: ${{ steps.result.outputs.validation_passed }}

    steps:
      - name: Checkout tag
        uses: actions/checkout@v5
        with:
          ref: ${{ inputs.tag_to_validate }}
          fetch-depth: 0

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Verify nixpkgs pinning
        id: verify_pin
        run: |
          echo "## Verifying Nixpkgs Pinning" >> $GITHUB_STEP_SUMMARY

          # Check that flake.nix uses commit hash, not branch
          if grep -q 'github:NixOS/nixpkgs/nixos-unstable' flake.nix; then
            echo "ERROR: flake.nix still references branch instead of commit hash" >> $GITHUB_STEP_SUMMARY
            echo "pinned=false" >> $GITHUB_OUTPUT
            exit 1
          fi

          # Extract commit hash from flake.nix
          PINNED_COMMIT=$(grep 'github:NixOS/nixpkgs/' flake.nix | sed 's|.*github:NixOS/nixpkgs/\([a-f0-9]*\).*|\1|')
          echo "pinned_commit=$PINNED_COMMIT" >> $GITHUB_OUTPUT
          echo "pinned=true" >> $GITHUB_OUTPUT

          echo "**Pinned to commit:** \`$PINNED_COMMIT\`" >> $GITHUB_STEP_SUMMARY

      - name: Run flake check
        id: flake_check
        continue-on-error: true
        run: |
          echo "## Running Flake Check" >> $GITHUB_STEP_SUMMARY

          nix flake check --all-systems --no-build --show-trace

          if [ $? -eq 0 ]; then
            echo "flake_check_passed=true" >> $GITHUB_OUTPUT
            echo "Flake check passed for all systems" >> $GITHUB_STEP_SUMMARY
          else
            echo "flake_check_passed=false" >> $GITHUB_OUTPUT
            echo "Flake check failed" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Verify apps exist
        id: verify_apps
        continue-on-error: true
        run: |
          echo "## Verifying Apps Exist" >> $GITHUB_STEP_SUMMARY

          ERRORS=0

          # Check if apps are defined in flake
          for app in sync check migrate-governance create-pack import-policy fetch-license list-licenses extract-config; do
            echo "Verifying app: $app"
            if nix flake show --json | jq -e ".apps.\"x86_64-linux\".\"$app\"" > /dev/null 2>&1; then
              echo "- **$app**: Found" >> $GITHUB_STEP_SUMMARY
            else
              echo "- **$app**: Missing" >> $GITHUB_STEP_SUMMARY
              ERRORS=$((ERRORS + 1))
            fi
          done

          echo "verify_errors=$ERRORS" >> $GITHUB_OUTPUT

          if [ $ERRORS -eq 0 ]; then
            echo "apps_verified=true" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "All apps verified successfully" >> $GITHUB_STEP_SUMMARY
          else
            echo "apps_verified=false" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Failed to verify $ERRORS apps" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Test sync and check apps
        id: test_apps
        continue-on-error: true
        run: |
          echo "## Testing Apps" >> $GITHUB_STEP_SUMMARY

          # Test sync with dry-run
          if nix run .#sync -- --dry-run; then
            echo "- **sync --dry-run**: Passed" >> $GITHUB_STEP_SUMMARY
            SYNC_PASS=true
          else
            echo "- **sync --dry-run**: Failed" >> $GITHUB_STEP_SUMMARY
            SYNC_PASS=false
          fi

          # Test check (expected to fail since no policies materialized)
          nix run .#check || true
          echo "- **check**: Ran (failure expected without materialized policies)" >> $GITHUB_STEP_SUMMARY

          # Test list-licenses
          if nix run .#list-licenses; then
            echo "- **list-licenses**: Passed" >> $GITHUB_STEP_SUMMARY
            LIST_PASS=true
          else
            echo "- **list-licenses**: Failed" >> $GITHUB_STEP_SUMMARY
            LIST_PASS=false
          fi

          if [ "$SYNC_PASS" = "true" ] && [ "$LIST_PASS" = "true" ]; then
            echo "apps_tested=true" >> $GITHUB_OUTPUT
          else
            echo "apps_tested=false" >> $GITHUB_OUTPUT
          fi

      - name: Determine validation result
        id: result
        run: |
          FLAKE_CHECK="${{ steps.flake_check.outputs.flake_check_passed }}"
          APPS_VERIFIED="${{ steps.verify_apps.outputs.apps_verified }}"
          APPS_TESTED="${{ steps.test_apps.outputs.apps_tested }}"

          if [ "$FLAKE_CHECK" = "true" ] && [ "$APPS_VERIFIED" = "true" ] && [ "$APPS_TESTED" = "true" ]; then
            echo "validation_passed=true" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "---" >> $GITHUB_STEP_SUMMARY
            echo "**Validation Result:** All checks passed" >> $GITHUB_STEP_SUMMARY
          else
            echo "validation_passed=false" >> $GITHUB_OUTPUT
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "---" >> $GITHUB_STEP_SUMMARY
            echo "**Validation Result:** Validation failed" >> $GITHUB_STEP_SUMMARY
            echo "- Flake check: $FLAKE_CHECK" >> $GITHUB_STEP_SUMMARY
            echo "- Apps verified: $APPS_VERIFIED" >> $GITHUB_STEP_SUMMARY
            echo "- Apps tested: $APPS_TESTED" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Create issue on failure
        if: steps.result.outputs.validation_passed != 'true'
        uses: actions/github-script@v7
        env:
          TAG: ${{ inputs.tag_to_validate }}
          COMMIT: ${{ steps.verify_pin.outputs.pinned_commit }}
          FLAKE_CHECK: ${{ steps.flake_check.outputs.flake_check_passed }}
          APPS_VERIFIED: ${{ steps.verify_apps.outputs.apps_verified }}
          APPS_TESTED: ${{ steps.test_apps.outputs.apps_tested }}
          VERIFY_ERRORS: ${{ steps.verify_apps.outputs.verify_errors }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          script: |
            const tag = process.env.TAG;
            const commit = process.env.COMMIT;
            const flakeCheck = process.env.FLAKE_CHECK;
            const appsVerified = process.env.APPS_VERIFIED;
            const appsTested = process.env.APPS_TESTED;
            const verifyErrors = process.env.VERIFY_ERRORS;
            const runUrl = process.env.RUN_URL;

            const title = 'Nixpkgs validation failed for ' + tag;
            const body = '## Validation Failure\n\n' +
              'The nixpkgs update validation failed for tag `' + tag + '`.\n\n' +
              '**Pinned commit:** `' + commit + '`\n\n' +
              '**Validation Results:**\n' +
              '- Flake check: ' + flakeCheck + '\n' +
              '- Apps verified: ' + appsVerified + '\n' +
              '- Apps tested: ' + appsTested + '\n\n' +
              '**Verification errors:** ' + verifyErrors + '\n\n' +
              '**Workflow run:** ' + runUrl + '\n\n' +
              '### Next Steps\n\n' +
              '1. Review the workflow logs for specific errors\n' +
              '2. If nixpkgs commit is problematic, wait for next update cycle\n' +
              '3. If baseline code needs fixes, make corrections and re-run validation\n' +
              '4. Manual rollback: `git tag -f ' + tag + ' PREVIOUS_COMMIT && git push -f origin ' + tag + '`';

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['automated', 'nixpkgs-update', 'validation-failure']
            });

  create-promotion-pr:
    needs: validate
    if: needs.validate.outputs.validation_passed == 'true' && inputs.promote_on_success
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          ref: main
          fetch-depth: 0

      - name: Get validated commit
        id: commit
        run: |
          VALIDATED_COMMIT=$(git rev-parse ${{ inputs.tag_to_validate }})
          echo "commit_hash=$VALIDATED_COMMIT" >> $GITHUB_OUTPUT
          SHORT_HASH="${VALIDATED_COMMIT:0:12}"
          echo "short_hash=$SHORT_HASH" >> $GITHUB_OUTPUT

      - name: Create marker file
        run: |
          BRANCH_NAME="promote-${{ steps.commit.outputs.short_hash }}"

          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Delete remote branch if it exists
          git push origin --delete "$BRANCH_NAME" 2>/dev/null || true

          # Remove marker file if it exists to ensure we have a change to commit
          rm -f .stable-candidate

          # Create and push new branch
          git checkout -b "$BRANCH_NAME"
          echo "${{ steps.commit.outputs.commit_hash }}" > .stable-candidate
          git add .stable-candidate
          git commit -m "Mark ${{ steps.commit.outputs.short_hash }} as stable candidate"
          git push origin "$BRANCH_NAME"

      - name: Create pull request
        uses: actions/github-script@v7
        env:
          COMMIT: ${{ steps.commit.outputs.commit_hash }}
          SHORT_HASH: ${{ steps.commit.outputs.short_hash }}
          TAG: ${{ inputs.tag_to_validate }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          script: |
            const commit = process.env.COMMIT;
            const shortHash = process.env.SHORT_HASH;
            const tag = process.env.TAG;
            const runUrl = process.env.RUN_URL;
            const branchName = 'promote-' + shortHash;

            // Close any existing promotion PRs (not just from this branch)
            const existingPRs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });

            const promotionPRs = existingPRs.data.filter(pr =>
              pr.head.ref.startsWith('promote-') &&
              pr.labels.some(label => label.name === 'promote-to-stable')
            );

            for (const pr of promotionPRs) {
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                state: 'closed'
              });
              console.log('Closed existing promotion PR #' + pr.number + ' (' + pr.head.ref + ')');
            }

            const title = 'Promote ' + tag + ' to stable (' + shortHash + ')';
            const body = '## Validation Passed\n\n' +
              'The validation workflow has successfully validated commit `' + commit + '`.\n\n' +
              '**Tag:** `' + tag + '`\n' +
              '**Commit:** `' + commit + '`\n\n' +
              '### Validation Results\n\n' +
              '- ✓ Nixpkgs pinning verified\n' +
              '- ✓ Flake check passed (all systems)\n' +
              '- ✓ Apps verified\n' +
              '- ✓ Apps tested\n\n' +
              '**Validation workflow:** ' + runUrl + '\n\n' +
              '### Next Steps\n\n' +
              '1. Review the validation results\n' +
              '2. Merge this PR to promote to stable\n' +
              '3. The stable tag will be automatically updated on merge\n\n' +
              '---\n\n' +
              '*Merging this PR will update the `stable` tag to point to `' + commit + '`.*';

            const pr = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              head: branchName,
              base: 'main'
            });

            // Add labels to the PR
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.data.number,
              labels: ['automated', 'promote-to-stable']
            });

            console.log('Created PR #' + pr.data.number + ' with labels');
