name: NixLine Policy Sync (reusable)

on:
  workflow_call:
    inputs:
      baseline_ref:
        description: 'Baseline reference (branch/tag) to sync from'
        required: false
        type: string
        default: 'stable'

permissions:
  contents: write
  issues: write

jobs:
  policy-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check policy compliance
        id: check
        continue-on-error: true
        run: |
          nix run .#check
          echo "check_result=$?" >> $GITHUB_OUTPUT

      - name: Sync policies if out of date
        id: sync
        if: steps.check.outputs.check_result != '0'
        continue-on-error: true
        run: |
          nix run .#sync
          echo "sync_result=$?" >> $GITHUB_OUTPUT

      - name: Check for changes
        id: git-check
        if: steps.check.outputs.check_result != '0' && steps.sync.outputs.sync_result == '0'
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "sync policies from baseline

          Automated policy sync from nixline-baseline@${{ inputs.baseline_ref }}"
          git push

      - name: Create issue on sync failure
        if: steps.sync.outputs.sync_result != '0' && steps.sync.outputs.sync_result != ''
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Policy sync failed',
              body: `## Policy Sync Failure

              The automated policy sync workflow failed to materialize policies from the baseline.

              **Baseline reference:** \`${{ inputs.baseline_ref }}\`
              **Workflow run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

              ### Next Steps

              Review the workflow logs to identify the sync failure. Common causes include:
              - Baseline flake evaluation errors
              - Network issues accessing the baseline repository
              - Invalid policy pack configuration

              Once resolved, the next scheduled sync will retry automatically.`,
              labels: ['automated', 'policy', 'sync-failure']
            });

      - name: Policy sync complete
        if: steps.check.outputs.check_result == '0'
        run: |
          echo "Policies are already in sync with baseline"
