name: NixLine Policy Sync (reusable)

on:
  workflow_call:
    inputs:
      baseline_ref:
        description: 'Baseline reference (branch/tag) to sync from'
        required: false
        type: string
        default: 'stable'

permissions:
  contents: write

jobs:
  policy-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v24
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - name: Check policy compliance
        id: check
        continue-on-error: true
        run: |
          nix run .#check
          echo "check_result=$?" >> $GITHUB_OUTPUT

      - name: Sync policies if out of date
        if: steps.check.outputs.check_result != '0'
        run: |
          nix run .#sync

      - name: Check for changes
        id: git-check
        if: steps.check.outputs.check_result != '0'
        run: |
          if git diff --quiet; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes
        if: steps.git-check.outputs.has_changes == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "sync policies from baseline

          Automated policy sync from nixline-baseline@${{ inputs.baseline_ref }}"
          git push

      - name: Policy sync complete
        if: steps.check.outputs.check_result == '0'
        run: |
          echo "Policies are already in sync with baseline"
