name: Update Stable Tag on Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-stable:
    uses: ./.github/workflows/update-stable-tag.yml
    with:
      tag_name: stable
      target_branch: main
