#
# Update Stable Tag on Push
#
# Automatically updates the stable tag when changes are pushed to main branch.
# Ensures the stable tag always points to the latest validated changes on
# the main branch for organization-wide workflow consistency.
#
# Triggered by: push to main branch
# Purpose: Automatic stable tag maintenance
# Features: Stable tag updates, main branch tracking, workflow version control
#

name: Update Stable Tag on Push

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  wait-for-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for validation to complete
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.sha }}
          check-name: 'validate'
          repo-token: ${{ github.token }}
          wait-interval: 10

  update-stable:
    needs: [wait-for-validation]
    uses: ./.github/workflows/update-stable-tag.yml
    with:
      tag_name: stable
      target_branch: main
